AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create cross-account role for sending findings to AWS Security Hub'
Metadata:
  Version: 0.7
Parameters:
  TargetHubAccountId:
    Type: String
    MaxLength: 12
    MinLength: 12
    Description: AWS Account ID (12 digits) of the account where AWS Security Hub is receiving findings
Resources:
  AssumeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: trend-micro-aff-forward-to-aws-security-hub
      Policies:
          -
            PolicyName: "ForwardFindingsToAwsSecurityHub"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: "Allow"
                  Action: "securityhub:BatchImportFindings"
                  Resource: "*"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: 
            "AWS": !Join [ "", [ "arn:aws:iam::", !Ref TargetHubAccountId, ":root" ] ]
          Action:
          - sts:AssumeRole
          Condition:
            Bool:
              "aws:MultiFactorAuthPresent": "False"